---
sidebar: sidebar
permalink: calculate-evs-savings.html
keywords: vm workloads, deploy fsx, deploy storage for vms, evs, savings, calculate, tco
summary: Calculate how much you can save by using Amazon EVS with FSx for ONTAP.
---

= Explore savings for Amazon Elastic VMware Service with NetApp Workload Factory
:icons: font
:imagesdir: ./media/

[.lead]
Explore potential savings for migrating your VMware workloads to Amazon Elastic VMware Service (EVS). The calculator enables you to compare costs of using Amazon EVS with and without Amazon FSx for NetApp ONTAP as storage.

If the savings calculator determines that the most cost-effective storage is FSx for ONTAP, you can create a detailed assessment, which provides a migration plan that you can review before using. You can then use the Codebox to generate Infrastructure-as-Code templates.

== Explore savings for EVS environments
Follow these steps to explore potential savings for a planned migration to an Amazon EVS environment. 

NOTE: Before proceeding, review the disclaimer at the bottom of the savings calculator to understand more about how the pricing estimates are calculated.

.Steps

. Log in to Workload Factory using one of the https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].

. From the VMware workloads tile, select *Explore savings* and then *Amazon Elastic VMware Service (EVS)*. The savings calculator is displayed.
+
The *Environment preferences* pane provides sliders that you can adjust depending on your environment's needs.
. Adjust the following sliders as needed to see real-time savings calculations for the values that you choose. If using a keyboard, you can make small adjustments using the arrow keys:
.. *Required physical CPU (count)*
.. *Required physical memory (GiB)*
.. *Required VM storage (TiB)*
.. *EVS billing plan*
. Do one of the following:
* To use the migration advisor to link:launch-migration-advisor-evs-manual.html[create a deployment plan] for an Amazon EVS environment, select *Create a detailed assessment*.
* Select *Close* to close the TCO calculator.
