---
sidebar: sidebar
permalink: deploy-fsx-file-system-native.html
keywords: vm workloads, deploy fsx, deploy storage for vms
summary: After you verify that the recommended FSx for ONTAP file system, or file systems in some cases, meets your exact requirements, you can use workload factory to deploy the system in your AWS environment.
---

= Deploy the VMware workloads recommended FSx for ONTAP file system
:icons: font
:imagesdir: ./media/

[.lead]
After you verify that the recommended FSx for ONTAP file system (or multiple file systems in some cases) meets your exact requirements, you can use workload factory to deploy the system in your AWS environment.

Follow the instructions in link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html[Create an FSx for ONTAP file system in BlueXP workload factory^] to deploy the FSx for ONTAP file system. You can use the *Advanced create* steps to fully customize the file system.

////

Depending on the policy and permissions that you added to your workload factory account, you can deploy the FSx for ONTAP file system completely using workload factory (using Automate mode). If you have fewer permissions (Read mode), or no permissions (Basic mode), you'll need to use the CloudFormation information from the Codebox and deploy the FSx for ONTAP file system yourself in AWS.

.Requirements for deployments to Amazon EC2

* The root volume of the FSx for ONTAP file system must be created as an EBS volume.

.Steps

. At the bottom of the *Review plan* page, select *Deploy* and the Create an FSx for ONTAP file system page is displayed.
+
Most of the fields that define your FSx for ONTAP file system are completed based on the information you provided, but there are a few fields that you need to complete in this page.
+
You can use the Quick create or Advanced create option. Advanced create offers a few additional storage parameters that you can customize. https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html[See what these two options offer]. 

. *AWS credentials*: Select or add credentials that will give workload factory the permissions necessary to create your FSx for ONTAP file system directly. You can also select the CloudFormation code from Codebox and deploy the FSx for ONTAP file system yourself in AWS.

. *File system name*: Enter the name that you want to use for this FSx for ONTAP file system.

. *Tags*: Optionally you can add tags to categorize this FSx for ONTAP file system.

. In the "Network & security" section, enter the following information:

+
.. *Region & VPC*: Select the Region and the VPC where the FSx for ONTAP file system will be deployed.
+
If you are deploying to VMware Cloud on AWS, ensure you deploy it in a VPC that is different than the VPC where the VMware Cloud on AWS is deployed.
.. *Security group*: When using the *Advanced create* option, you can select the default security group for the FSx for ONTAP VPC so that all traffic can access the FSx for ONTAP file system. 
+
You can add an inbound rule that restricts what other AWS services can access the FSx for ONTAP file system. This will block the amount of services that are open. These are the minimum ports and protocols:
+
[cols="15,10,55",width=80%,options="header"]
|===
| Protocols
| Ports
| Purpose
| TCP, UDP | 111 | Portmapper (used to negotiate which ports are used in NFS requests)
| TCP, UDP | 635 | NFS mountd (receives NFS mount requests)
| TCP, UDP | 2049 | NFS network traffic
| TCP, UDP | 4045 | Network Lock Manager (NLM, lockd) - Handles lock requests.
| TCP, UDP | 4046 | Network Status Monitor (NSM, statd) - Notifies NFS clients about reboots of the server for lock management.
|===

+
.. *Availability zone*: Select the Availability Zone and the Subnet.
+
You should select the same availability zone as where your VMware SDDC is deployed if you want to avoid charges for cross-AZ traffic.
.. *Encryption*: When using the *Advanced create* option, you can select the AWS encryption key name from the dropdown.
.. *Datastore access control*: When using the *Advanced create* option, you can select whether all hosts can access the datastores or whether only certain vSphere cluster nodes on a specific subnet can access the datastores.

. In the "File system details" section, enter the following information:

+
.. *ONTAP credentials*: Enter and confirm the ONTAP password.
.. *Storage VM credentials* (Advanced create only): Enter and confirm the storage VM password. The password can be specific to this file system, or you can use the same password entered for ONTAP credentials.

. In the *Summary* section, you can view the FSx for ONTAP file system and datastore configuration that the VMware migration advisor has designed based on your information.

. Select *Create* to deploy the FSx for ONTAP file system. This process can take up to 2 hours. 
+
Optionally, in the Codebox window you can select *Redirect to CloudFormation* to create the file system using a CloudFormation stack.
+
In either case, you can you can monitor the creation progress in CloudFormation.

.Result

The FSx for ONTAP file system is deployed.

////
