settings:
  name: VMware workloads
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
sidebar: 
  entries:
    - title: VMware workloads docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
        - title: Known limitations
          url: /limitations.html
    - title: Get started
      entries:
        - title: Learn about Workload Factory for VMware
          url: /onboarding-advisor-overview.html
        - title: Quick start
          url: /quick-start.html
    - title: Use the VMware Cloud on AWS onboarding advisor
      entries:
        - title: Capture your current VM configurations
          url: /capture-vm-configurations.html
        - title: Create a deployment plan using the onboarding advisor
          url: /launch-onboarding-advisor.html
        - title: Deploy the recommended FSx for ONTAP file system
          url: /deploy-fsx-file-system.html
        - title: Migrate your data to the new infrastructure
          url: /migrate-data.html
        - title: What you can do next
          url: /whats-next.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /support-registration.html
        - title: Get help
          url: /get-help.html    
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Workload Factory
  repo: workload-family