settings:
  name: VMware workloads 
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
  release_notes_autogen:
    release_notes_repo: workload-relnotes
sidebar: 
  entries:
    - title: VMware workloads docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about NetApp Workload Factory for VMware
          url: /learn-about-vmware-workloads.html
        - title: Quick start for migrating to Amazon EVS
          url: /quick-start-evs.html        
        - title: Quick start for migrating to Amazon EC2
          url: /quick-start-native.html
        - title: Quick start for migrating to VMware Cloud on AWS
          url: /quick-start.html
        - title: Explore the VMware planning center
          url: /explore-planning-center.html
    - title: Use the VMware planning center
      entries:
        - title: Upload VM inventory data
          url: /upload-vm-inventory.html
        - title: Migrate to Amazon Elastic VMware Service
          entries:
          - title: Explore savings
            url: /calculate-evs-savings.html
          - title: Manually create a deployment plan
            url: /launch-migration-advisor-evs-manual.html
          - title: Create a deployment plan using the migration advisor
            url: /launch-migration-advisor-evs.html
          - title: Deploy the recommended FSx for ONTAP file system
            url: /deploy-fsx-file-system-evs.html
        - title: Migrate to Amazon EC2
          entries:
#          - title: Capture your current VM configurations
#            url: /capture-vm-configurations-native.html
          - title: Create a deployment plan using the migration advisor
            url: /launch-onboarding-advisor-native.html
          - title: Deploy the recommended FSx for ONTAP file system
            url: /deploy-fsx-file-system-native.html
#          - title: Connect FSx for ONTAP to VMware Cloud on AWS
#            url: /connect-sddc-to-fsx.html
         # - title: Migrate your data to the new infrastructure
         #   url: /migrate-data-native.html
        - title: Migrate to VMware Cloud on AWS
          entries:
#          - title: Capture your current VM configurations
#            url: /capture-vm-configurations.html
          - title: Create a deployment plan using the migration advisor
            url: /launch-onboarding-advisor.html
          - title: Deploy the recommended FSx for ONTAP file system
            url: /deploy-fsx-file-system.html
          - title: Connect FSx for ONTAP to VMware Cloud on AWS
            url: /connect-sddc-to-fsx.html
          - title: Migrate your data to the new infrastructure
            url: /migrate-data.html
    - title: Administer and monitor
      entries:
        - title: Implement well-architected file system configurations
          url: /view-evs-well-architected.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /support-registration.html
        - title: Get help
          url: /get-help.html    
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: NetApp Workload Factory
  repo: workload-family